sonar.projectKey=YOUR_ORG_YOUR_PROJECT
sonar.organization=YOUR_ORG

sonar.projectName=TripMate Expo App
sonar.projectVersion=1.0.0

sonar.sources=app,components
sonar.tests=__tests__
sonar.test.inclusions=**/__tests__/**/*.test.tsx,**/__tests__/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.tsx,**/*.test.ts,**/node_modules/**

sonar.typescript.tsconfigPath=tsconfig.json
