sonar.projectKey=L02-T1_TripMate
sonar.organization=l02-t1

# source code
sonar.sources=app

# test files
sonar.tests=app/__tests__

# coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# encoding
sonar.sourceEncoding=UTF-8